/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.apis

import io.kotlintest.specs.ShouldSpec

class CharacterBangumiApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CharacterBangumiApi
        //val apiInstance = CharacterBangumiApi()

        // to test collectCharacterByCharacterIdAndUserId
        should("test collectCharacterByCharacterIdAndUserId") {
            // uncomment below to test collectCharacterByCharacterIdAndUserId
            //val characterId : kotlin.Int = 56 // kotlin.Int | 角色 ID
            //apiInstance.collectCharacterByCharacterIdAndUserId(characterId)
        }

        // to test getCharacterById
        should("test getCharacterById") {
            // uncomment below to test getCharacterById
            //val characterId : kotlin.Int = 56 // kotlin.Int | 角色 ID
            //val result : CharacterDetail = apiInstance.getCharacterById(characterId)
            //result shouldBe ("TODO")
        }

        // to test getCharacterImageById
        should("test getCharacterImageById") {
            // uncomment below to test getCharacterImageById
            //val characterId : kotlin.Int = 56 // kotlin.Int | 角色 ID
            //val type : kotlin.String = type_example // kotlin.String | 枚举值 {small|grid|large|medium}
            //apiInstance.getCharacterImageById(characterId, type)
        }

        // to test getRelatedPersonsByCharacterId
        should("test getRelatedPersonsByCharacterId") {
            // uncomment below to test getRelatedPersonsByCharacterId
            //val characterId : kotlin.Int = 56 // kotlin.Int | 角色 ID
            //val result : kotlin.collections.List<CharacterPerson> = apiInstance.getRelatedPersonsByCharacterId(characterId)
            //result shouldBe ("TODO")
        }

        // to test getRelatedSubjectsByCharacterId
        should("test getRelatedSubjectsByCharacterId") {
            // uncomment below to test getRelatedSubjectsByCharacterId
            //val characterId : kotlin.Int = 56 // kotlin.Int | 角色 ID
            //val result : kotlin.collections.List<V0RelatedSubject> = apiInstance.getRelatedSubjectsByCharacterId(characterId)
            //result shouldBe ("TODO")
        }

        // to test uncollectCharacterByCharacterIdAndUserId
        should("test uncollectCharacterByCharacterIdAndUserId") {
            // uncomment below to test uncollectCharacterByCharacterIdAndUserId
            //val characterId : kotlin.Int = 56 // kotlin.Int | 角色 ID
            //apiInstance.uncollectCharacterByCharacterIdAndUserId(characterId)
        }

    }
}
