/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.apis

import io.kotlintest.specs.ShouldSpec

class EpisodeBangumiApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EpisodeBangumiApi
        //val apiInstance = EpisodeBangumiApi()

        // to test getEpisodeById
        should("test getEpisodeById") {
            // uncomment below to test getEpisodeById
            //val episodeId : kotlin.Int = 56 // kotlin.Int | 章节 ID
            //val result : EpisodeDetail = apiInstance.getEpisodeById(episodeId)
            //result shouldBe ("TODO")
        }

        // to test getEpisodes
        should("test getEpisodes") {
            // uncomment below to test getEpisodes
            //val subjectId : kotlin.Int = 56 // kotlin.Int | 条目 ID
            //val type : EpType = 56 // EpType | 参照章节的`type`
            //val limit : kotlin.Int = 56 // kotlin.Int | 分页参数
            //val offset : kotlin.Int = 56 // kotlin.Int | 分页参数
            //val result : PagedEpisode = apiInstance.getEpisodes(subjectId, type, limit, offset)
            //result shouldBe ("TODO")
        }

    }
}
