/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.apis

import io.kotlintest.specs.ShouldSpec

class IndexBangumiApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of IndexBangumiApi
        //val apiInstance = IndexBangumiApi()

        // to test addSubjectToIndexByIndexId
        should("test addSubjectToIndexByIndexId") {
            // uncomment below to test addSubjectToIndexByIndexId
            //val indexId : kotlin.Int = 56 // kotlin.Int | 目录 ID
            //val indexSubjectAddInfo : IndexSubjectAddInfo =  // IndexSubjectAddInfo |
            //apiInstance.addSubjectToIndexByIndexId(indexId, indexSubjectAddInfo)
        }

        // to test collectIndexByIndexIdAndUserId
        should("test collectIndexByIndexIdAndUserId") {
            // uncomment below to test collectIndexByIndexIdAndUserId
            //val indexId : kotlin.Int = 56 // kotlin.Int | 目录 ID
            //apiInstance.collectIndexByIndexIdAndUserId(indexId)
        }

        // to test delelteSubjectFromIndexByIndexIdAndSubjectID
        should("test delelteSubjectFromIndexByIndexIdAndSubjectID") {
            // uncomment below to test delelteSubjectFromIndexByIndexIdAndSubjectID
            //val indexId : kotlin.Int = 56 // kotlin.Int | 目录 ID
            //val subjectId : kotlin.Int = 56 // kotlin.Int | 条目 ID
            //apiInstance.delelteSubjectFromIndexByIndexIdAndSubjectID(indexId, subjectId)
        }

        // to test editIndexById
        should("test editIndexById") {
            // uncomment below to test editIndexById
            //val indexId : kotlin.Int = 56 // kotlin.Int | 目录 ID
            //val indexBasicInfo : IndexBasicInfo =  // IndexBasicInfo |
            //val result : Index = apiInstance.editIndexById(indexId, indexBasicInfo)
            //result shouldBe ("TODO")
        }

        // to test editIndexSubjectsByIndexIdAndSubjectID
        should("test editIndexSubjectsByIndexIdAndSubjectID") {
            // uncomment below to test editIndexSubjectsByIndexIdAndSubjectID
            //val indexId : kotlin.Int = 56 // kotlin.Int | 目录 ID
            //val subjectId : kotlin.Int = 56 // kotlin.Int | 条目 ID
            //val indexSubjectEditInfo : IndexSubjectEditInfo =  // IndexSubjectEditInfo |
            //apiInstance.editIndexSubjectsByIndexIdAndSubjectID(indexId, subjectId, indexSubjectEditInfo)
        }

        // to test getIndexById
        should("test getIndexById") {
            // uncomment below to test getIndexById
            //val indexId : kotlin.Int = 56 // kotlin.Int | 目录 ID
            //val result : Index = apiInstance.getIndexById(indexId)
            //result shouldBe ("TODO")
        }

        // to test getIndexSubjectsByIndexId
        should("test getIndexSubjectsByIndexId") {
            // uncomment below to test getIndexSubjectsByIndexId
            //val indexId : kotlin.Int = 56 // kotlin.Int | 目录 ID
            //val type : SubjectType =  // SubjectType | 条目类型
            //val limit : kotlin.Int = 56 // kotlin.Int | 分页参数
            //val offset : kotlin.Int = 56 // kotlin.Int | 分页参数
            //apiInstance.getIndexSubjectsByIndexId(indexId, type, limit, offset)
        }

        // to test newIndex
        should("test newIndex") {
            // uncomment below to test newIndex
            //val result : Index = apiInstance.newIndex()
            //result shouldBe ("TODO")
        }

        // to test uncollectIndexByIndexIdAndUserId
        should("test uncollectIndexByIndexIdAndUserId") {
            // uncomment below to test uncollectIndexByIndexIdAndUserId
            //val indexId : kotlin.Int = 56 // kotlin.Int | 目录 ID
            //apiInstance.uncollectIndexByIndexIdAndUserId(indexId)
        }

    }
}
