/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.apis

import io.kotlintest.specs.ShouldSpec

class OauthBangumiApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OauthBangumiApi
        //val apiInstance = OauthBangumiApi()

        // to test authorize
        should("test authorize") {
            // uncomment below to test authorize
            //val clientId : kotlin.String = clientId_example // kotlin.String | App ID，注册应用时获取
            //val responseType : kotlin.String = responseType_example // kotlin.String | 验证类型，目前仅支持 code
            //val redirectUri : kotlin.String = redirectUri_example // kotlin.String | 回调 URL，在后台设置的回调地址
            //val scope : kotlin.String = scope_example // kotlin.String | 请求权限，尚未实现
            //val state : kotlin.String = state_example // kotlin.String | 随机参数，随机生产的参数，便于开发者防止跨站攻击
            //apiInstance.authorize(clientId, responseType, redirectUri, scope, state)
        }

        // to test getAccessToken
        should("test getAccessToken") {
            // uncomment below to test getAccessToken
            //val accessTokenRequest : AccessTokenRequest =  // AccessTokenRequest |
            //val result : UserAccessToken = apiInstance.getAccessToken(accessTokenRequest)
            //result shouldBe ("TODO")
        }

    }
}
