/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.apis

import io.kotlintest.specs.ShouldSpec

class PersonBangumiApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PersonBangumiApi
        //val apiInstance = PersonBangumiApi()

        // to test collectPersonByPersonIdAndUserId
        should("test collectPersonByPersonIdAndUserId") {
            // uncomment below to test collectPersonByPersonIdAndUserId
            //val personId : kotlin.Int = 56 // kotlin.Int | 人物 ID
            //apiInstance.collectPersonByPersonIdAndUserId(personId)
        }

        // to test getPersonById
        should("test getPersonById") {
            // uncomment below to test getPersonById
            //val personId : kotlin.Int = 56 // kotlin.Int | 人物 ID
            //val result : PersonDetail = apiInstance.getPersonById(personId)
            //result shouldBe ("TODO")
        }

        // to test getPersonImageById
        should("test getPersonImageById") {
            // uncomment below to test getPersonImageById
            //val personId : kotlin.Int = 56 // kotlin.Int | 人物 ID
            //val type : kotlin.String = type_example // kotlin.String | 枚举值 {small|grid|large|medium}
            //apiInstance.getPersonImageById(personId, type)
        }

        // to test getRelatedCharactersByPersonId
        should("test getRelatedCharactersByPersonId") {
            // uncomment below to test getRelatedCharactersByPersonId
            //val personId : kotlin.Int = 56 // kotlin.Int | 人物 ID
            //val result : kotlin.collections.List<PersonCharacter> = apiInstance.getRelatedCharactersByPersonId(personId)
            //result shouldBe ("TODO")
        }

        // to test getRelatedSubjectsByPersonId
        should("test getRelatedSubjectsByPersonId") {
            // uncomment below to test getRelatedSubjectsByPersonId
            //val personId : kotlin.Int = 56 // kotlin.Int | 人物 ID
            //val result : kotlin.collections.List<V0RelatedSubject> = apiInstance.getRelatedSubjectsByPersonId(personId)
            //result shouldBe ("TODO")
        }

        // to test uncollectPersonByPersonIdAndUserId
        should("test uncollectPersonByPersonIdAndUserId") {
            // uncomment below to test uncollectPersonByPersonIdAndUserId
            //val personId : kotlin.Int = 56 // kotlin.Int | 人物 ID
            //apiInstance.uncollectPersonByPersonIdAndUserId(personId)
        }

    }
}
