/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.apis

import io.kotlintest.specs.ShouldSpec

class RevisionBangumiApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RevisionBangumiApi
        //val apiInstance = RevisionBangumiApi()

        // to test getCharacterRevisionByRevisionId
        should("test getCharacterRevisionByRevisionId") {
            // uncomment below to test getCharacterRevisionByRevisionId
            //val revisionId : kotlin.Int = 56 // kotlin.Int | 版本 ID
            //val result : CharacterRevision = apiInstance.getCharacterRevisionByRevisionId(revisionId)
            //result shouldBe ("TODO")
        }

        // to test getCharacterRevisions
        should("test getCharacterRevisions") {
            // uncomment below to test getCharacterRevisions
            //val characterId : kotlin.Int = 56 // kotlin.Int | 角色 ID
            //val limit : kotlin.Int = 56 // kotlin.Int | 分页参数
            //val offset : kotlin.Int = 56 // kotlin.Int | 分页参数
            //val result : PagedRevision = apiInstance.getCharacterRevisions(characterId, limit, offset)
            //result shouldBe ("TODO")
        }

        // to test getEpisodeRevisionByRevisionId
        should("test getEpisodeRevisionByRevisionId") {
            // uncomment below to test getEpisodeRevisionByRevisionId
            //val revisionId : kotlin.Int = 56 // kotlin.Int | 版本 ID
            //val result : DetailedRevision = apiInstance.getEpisodeRevisionByRevisionId(revisionId)
            //result shouldBe ("TODO")
        }

        // to test getEpisodeRevisions
        should("test getEpisodeRevisions") {
            // uncomment below to test getEpisodeRevisions
            //val episodeId : kotlin.Int = 56 // kotlin.Int | 章节 ID
            //val limit : kotlin.Int = 56 // kotlin.Int | 分页参数
            //val offset : kotlin.Int = 56 // kotlin.Int | 分页参数
            //val result : PagedRevision = apiInstance.getEpisodeRevisions(episodeId, limit, offset)
            //result shouldBe ("TODO")
        }

        // to test getPersonRevisionByRevisionId
        should("test getPersonRevisionByRevisionId") {
            // uncomment below to test getPersonRevisionByRevisionId
            //val revisionId : kotlin.Int = 56 // kotlin.Int | 历史版本 ID
            //val result : PersonRevision = apiInstance.getPersonRevisionByRevisionId(revisionId)
            //result shouldBe ("TODO")
        }

        // to test getPersonRevisions
        should("test getPersonRevisions") {
            // uncomment below to test getPersonRevisions
            //val personId : kotlin.Int = 56 // kotlin.Int | 角色 ID
            //val limit : kotlin.Int = 56 // kotlin.Int | 分页参数
            //val offset : kotlin.Int = 56 // kotlin.Int | 分页参数
            //val result : PagedRevision = apiInstance.getPersonRevisions(personId, limit, offset)
            //result shouldBe ("TODO")
        }

        // to test getSubjectRevisionByRevisionId
        should("test getSubjectRevisionByRevisionId") {
            // uncomment below to test getSubjectRevisionByRevisionId
            //val revisionId : kotlin.Int = 56 // kotlin.Int | 版本 ID
            //val result : SubjectRevision = apiInstance.getSubjectRevisionByRevisionId(revisionId)
            //result shouldBe ("TODO")
        }

        // to test getSubjectRevisions
        should("test getSubjectRevisions") {
            // uncomment below to test getSubjectRevisions
            //val subjectId : kotlin.Int = 56 // kotlin.Int | 条目 ID
            //val limit : kotlin.Int = 56 // kotlin.Int | 分页参数
            //val offset : kotlin.Int = 56 // kotlin.Int | 分页参数
            //val result : PagedRevision = apiInstance.getSubjectRevisions(subjectId, limit, offset)
            //result shouldBe ("TODO")
        }

    }
}
