/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.apis

import io.kotlintest.specs.ShouldSpec

class SearchBangumiApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SearchBangumiApi
        //val apiInstance = SearchBangumiApi()

        // to test searchSubjectByKeywords
        should("test searchSubjectByKeywords") {
            // uncomment below to test searchSubjectByKeywords
            //val keywords : kotlin.String = keywords_example // kotlin.String | 关键词 <br> 需要 URL Encode
            //val type : LegacySubjectType =  // LegacySubjectType | 条目类型，参考 [SubjectType](#model-Legacy_SubjectType)
            //val responseGroup : kotlin.String = responseGroup_example // kotlin.String | 返回数据大小 <br> 默认为 small
            //val start : kotlin.Int = 56 // kotlin.Int | 开始条数
            //val maxResults : kotlin.Int = 56 // kotlin.Int | 每页条数 <br> 最多 25
            //val result : SearchSubjectByKeywords200Response = apiInstance.searchSubjectByKeywords(keywords, type, responseGroup, start, maxResults)
            //result shouldBe ("TODO")
        }

    }
}
