/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.apis

import io.kotlintest.specs.ShouldSpec

class UserBangumiApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserBangumiApi
        //val apiInstance = UserBangumiApi()

        // to test getMyself
        should("test getMyself") {
            // uncomment below to test getMyself
            //val result : GetMyself200Response = apiInstance.getMyself()
            //result shouldBe ("TODO")
        }

        // to test getUserAvatarByName
        should("test getUserAvatarByName") {
            // uncomment below to test getUserAvatarByName
            //val username : kotlin.String = username_example // kotlin.String | 设置了用户名之后无法使用 UID。
            //val type : kotlin.String = type_example // kotlin.String | 枚举值 {small|large|medium}
            //apiInstance.getUserAvatarByName(username, type)
        }

        // to test getUserByName
        should("test getUserByName") {
            // uncomment below to test getUserByName
            //val username : kotlin.String = username_example // kotlin.String | 设置了用户名之后无法使用 UID。
            //val result : User = apiInstance.getUserByName(username)
            //result shouldBe ("TODO")
        }

    }
}
