FROM frolvlad/alpine-glibc:glibc-2.34

RUN apk add --no-cache tzdata && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
        echo "Asia/Shanghai" > /etc/timezone

ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en'

# We make four distinct layers so if there are application changes the library layers can be re-used
COPY build/native/nativeCompile/bangumi-bot /deployments/
COPY entrypoint.sh /deployments/
RUN chmod +x /deployments/entrypoint.sh

EXPOSE 8080

WORKDIR /deployments

ENTRYPOINT ["/bin/sh", "/deployments/entrypoint-native.sh"]
