/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


/**
 * - `0`: 未收藏 - `1`: 想看 - `2`: 看过 - `3`: 抛弃
 *
 * Values: _1,_2,_3
 */
@Serializable(with = EpisodeCollectionTypeSerializer::class)
enum class EpisodeCollectionType(val value: kotlin.Int) {

    _1(1),

    _2(2),

    _3(3);

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value.toString()

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is EpisodeCollectionType) "$data" else null

        /**
         * Returns a valid [EpisodeCollectionType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): EpisodeCollectionType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

internal object EpisodeCollectionTypeSerializer : KSerializer<EpisodeCollectionType> {
    override val descriptor = kotlin.Int.serializer().descriptor

    override fun deserialize(decoder: Decoder): EpisodeCollectionType {
        val value = decoder.decodeSerializableValue(kotlin.Int.serializer())
        return EpisodeCollectionType.values().firstOrNull { it.value == value }
            ?: throw IllegalArgumentException("Unknown enum value: $value")
    }

    override fun serialize(encoder: Encoder, value: EpisodeCollectionType) {
        encoder.encodeSerializableValue(kotlin.Int.serializer(), value.value)
    }
}


