/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 评分
 *
 * @param total 总评分人数
 * @param count
 * @param score 评分
 */
@Serializable

data class LegacySubjectSmallRating(

    /* 总评分人数 */
    @SerialName(value = "total")
    val total: kotlin.Int? = null,

    @SerialName(value = "count")
    val count: LegacySubjectSmallRatingCount? = null,

    /* 评分 */
    @Contextual @SerialName(value = "score")
    val score: Float? = null

) {


}

