/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


/**
 * 章节类型 <br> 0 = 本篇 <br> 1 = 特别篇 <br> 2 = OP <br> 3 = ED <br> 4 = 预告/宣传/广告 <br> 5 = MAD <br> 6 = 其他
 *
 * Values: _0,_1,_2,_3,_4,_5,_6
 */
@Serializable(with = LegacyEpisodeTypeSerializer::class)
enum class LegacyEpisodeType(val value: kotlin.Int) {

    _0(0),

    _1(1),

    _2(2),

    _3(3),

    _4(4),

    _5(5),

    _6(6);

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value.toString()

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is LegacyEpisodeType) "$data" else null

        /**
         * Returns a valid [LegacyEpisodeType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): LegacyEpisodeType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

internal object LegacyEpisodeTypeSerializer : KSerializer<LegacyEpisodeType> {
    override val descriptor = kotlin.Int.serializer().descriptor

    override fun deserialize(decoder: Decoder): LegacyEpisodeType {
        val value = decoder.decodeSerializableValue(kotlin.Int.serializer())
        return LegacyEpisodeType.values().firstOrNull { it.value == value }
            ?: throw IllegalArgumentException("Unknown enum value: $value")
    }

    override fun serialize(encoder: Encoder, value: LegacyEpisodeType) {
        encoder.encodeSerializableValue(kotlin.Int.serializer(), value.value)
    }
}


