/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param rank
 * @param total
 * @param count
 * @param score
 */
@Serializable

data class Rating (

    @SerialName(value = "rank")
    val rank: kotlin.Int,

    @SerialName(value = "total")
    val total: kotlin.Int,

    @SerialName(value = "count")
    val count: Count,

    @SerialName(value = "score")
    val score: kotlin.Float

) {


}

