/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param keyword
 * @param filter
 */
@Serializable

data class SearchCharactersRequest(

    @SerialName(value = "keyword")
    val keyword: kotlin.String,

    @SerialName(value = "filter")
    val filter: SearchCharactersRequestFilter? = null

) {


}

