/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


/**
 * 动画类型 - `0` 为 其他 - `1` 为 TV - `2` 为 OVA - `3` 为 Movie - `5` 为 WEB
 *
 * Values: Other,TV,OVA,Movie,WEB
 */
@Serializable(with = SubjectAnimeCategorySerializer::class)
enum class SubjectAnimeCategory(val value: kotlin.Int) {

    Other(0),

    TV(1),

    OVA(2),

    Movie(3),

    WEB(5);

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value.toString()

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is SubjectAnimeCategory) "$data" else null

        /**
         * Returns a valid [SubjectAnimeCategory] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): SubjectAnimeCategory? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

internal object SubjectAnimeCategorySerializer : KSerializer<SubjectAnimeCategory> {
    override val descriptor = kotlin.Int.serializer().descriptor

    override fun deserialize(decoder: Decoder): SubjectAnimeCategory {
        val value = decoder.decodeSerializableValue(kotlin.Int.serializer())
        return SubjectAnimeCategory.values().firstOrNull { it.value == value }
            ?: throw IllegalArgumentException("Unknown enum value: $value")
    }

    override fun serialize(encoder: Encoder, value: SubjectAnimeCategory) {
        encoder.encodeSerializableValue(kotlin.Int.serializer(), value.value)
    }
}


