/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


/**
 * - `1`: 想看 - `2`: 看过 - `3`: 在看 - `4`: 搁置 - `5`: 抛弃
 *
 * Values: Wish,Done,Doing,OnHold,Dropped
 */
@Serializable(with = SubjectCollectionTypeSerializer::class)
enum class SubjectCollectionType(val value: kotlin.Int) {

    Wish(1),

    Done(2),

    Doing(3),

    OnHold(4),

    Dropped(5);

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value.toString()

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is SubjectCollectionType) "$data" else null

        /**
         * Returns a valid [SubjectCollectionType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): SubjectCollectionType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

internal object SubjectCollectionTypeSerializer : KSerializer<SubjectCollectionType> {
    override val descriptor = kotlin.Int.serializer().descriptor

    override fun deserialize(decoder: Decoder): SubjectCollectionType {
        val value = decoder.decodeSerializableValue(kotlin.Int.serializer())
        return SubjectCollectionType.values().firstOrNull { it.value == value }
            ?: throw IllegalArgumentException("Unknown enum value: $value")
    }

    override fun serialize(encoder: Encoder, value: SubjectCollectionType) {
        encoder.encodeSerializableValue(kotlin.Int.serializer(), value.value)
    }
}


