/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


/**
 * 用户组 - 1 = 管理员 - 2 = Bangumi 管理猿 - 3 = 天窗管理猿 - 4 = 禁言用户 - 5 = 禁止访问用户 - 8 = 人物管理猿 - 9 = 维基条目管理猿 - 10 = 用户 - 11 = 维基人
 *
 * Values: Admin,BangumiAdmin,DoujinAdmin,MutedUser,BlockedUser,PersonAdmin,WikiAdmin,User,WikiUser
 */
@Serializable(with = UserGroupSerializer::class)
enum class UserGroup(val value: kotlin.Int) {

    Admin(1),

    BangumiAdmin(2),

    DoujinAdmin(3),

    MutedUser(4),

    BlockedUser(5),

    PersonAdmin(8),

    WikiAdmin(9),

    User(10),

    WikiUser(11);

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value.toString()

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is UserGroup) "$data" else null

        /**
         * Returns a valid [UserGroup] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): UserGroup? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

internal object UserGroupSerializer : KSerializer<UserGroup> {
    override val descriptor = kotlin.Int.serializer().descriptor

    override fun deserialize(decoder: Decoder): UserGroup {
        val value = decoder.decodeSerializableValue(kotlin.Int.serializer())
        return UserGroup.values().firstOrNull { it.value == value }
            ?: throw IllegalArgumentException("Unknown enum value: $value")
    }

    override fun serialize(encoder: Encoder, value: UserGroup) {
        encoder.encodeSerializableValue(kotlin.Int.serializer(), value.value)
    }
}


