/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param episode
 * @param type
 * @param updatedAt A int64 unix timestamp, `0` as unknown or un-recorded.
 */
@Serializable

data class UserEpisodeCollection (

    @SerialName(value = "episode")
    val episode: Episode,

    @Contextual @SerialName(value = "type")
    val type: EpisodeCollectionType,

    /* A int64 unix timestamp, `0` as unknown or un-recorded. */
    @SerialName(value = "updated_at")
    val updatedAt: kotlin.Int

) : kotlin.collections.HashMap<String, kotlin.Any>() {


}

