/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import io.kotlintest.specs.ShouldSpec

class AccessTokenRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AccessTokenRequest
        //val modelInstance = AccessTokenRequest()

        // to test the property `grantType` - 授权方式，`authorization_code` 需要用到code，refresh_token需要用到
        should("test grantType") {
            // uncomment below to test the property
            //modelInstance.grantType shouldBe ("TODO")
        }

        // to test the property `clientId` - App ID
        should("test clientId") {
            // uncomment below to test the property
            //modelInstance.clientId shouldBe ("TODO")
        }

        // to test the property `clientSecret` - App Secret
        should("test clientSecret") {
            // uncomment below to test the property
            //modelInstance.clientSecret shouldBe ("TODO")
        }

        // to test the property `redirectUri` - 回调 URL
        should("test redirectUri") {
            // uncomment below to test the property
            //modelInstance.redirectUri shouldBe ("TODO")
        }

        // to test the property `refreshToken` - Refresh Token
        should("test refreshToken") {
            // uncomment below to test the property
            //modelInstance.refreshToken shouldBe ("TODO")
        }

        // to test the property `code` - 验证代码
        should("test code") {
            // uncomment below to test the property
            //modelInstance.code shouldBe ("TODO")
        }

        // to test the property `state` - 随机参数
        should("test state") {
            // uncomment below to test the property
            //modelInstance.state shouldBe ("TODO")
        }

    }
}
