/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import io.kotlintest.specs.ShouldSpec

class EpisodeCollectionTypeTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EpisodeCollectionType
        //val modelInstance = EpisodeCollectionType()

    }
}
