/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import io.kotlintest.specs.ShouldSpec

class GetCalendar200ResponseInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetCalendar200ResponseInner
        //val modelInstance = GetCalendar200ResponseInner()

        // to test the property `weekday`
        should("test weekday") {
            // uncomment below to test the property
            //modelInstance.weekday shouldBe ("TODO")
        }

        // to test the property `items`
        should("test items") {
            // uncomment below to test the property
            //modelInstance.items shouldBe ("TODO")
        }

    }
}
