/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import io.kotlintest.specs.ShouldSpec

class GetCalendar200ResponseInnerWeekdayTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetCalendar200ResponseInnerWeekday
        //val modelInstance = GetCalendar200ResponseInnerWeekday()

        // to test the property `en`
        should("test en") {
            // uncomment below to test the property
            //modelInstance.en shouldBe ("TODO")
        }

        // to test the property `cn`
        should("test cn") {
            // uncomment below to test the property
            //modelInstance.cn shouldBe ("TODO")
        }

        // to test the property `ja`
        should("test ja") {
            // uncomment below to test the property
            //modelInstance.ja shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

    }
}
