/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import moe.kurenai.bangumi.models.IndexSubjectEditInfo

class IndexSubjectEditInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of IndexSubjectEditInfo
        //val modelInstance = IndexSubjectEditInfo()

        // to test the property `sort` - 排序条件，越小越靠前
        should("test sort") {
            // uncomment below to test the property
            //modelInstance.sort shouldBe ("TODO")
        }

        // to test the property `comment`
        should("test comment") {
            // uncomment below to test the property
            //modelInstance.comment shouldBe ("TODO")
        }

    }
}
