/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import moe.kurenai.bangumi.models.LegacyUser
import moe.kurenai.bangumi.models.LegacyUserAvatar
import moe.kurenai.bangumi.models.LegacyUserGroup

class LegacyUserTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LegacyUser
        //val modelInstance = LegacyUser()

        // to test the property `id` - 用户 id
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `url` - 用户主页地址
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `username` - 用户名
        should("test username") {
            // uncomment below to test the property
            //modelInstance.username shouldBe ("TODO")
        }

        // to test the property `nickname` - 昵称
        should("test nickname") {
            // uncomment below to test the property
            //modelInstance.nickname shouldBe ("TODO")
        }

        // to test the property `avatar`
        should("test avatar") {
            // uncomment below to test the property
            //modelInstance.avatar shouldBe ("TODO")
        }

        // to test the property `sign` - 签名
        should("test sign") {
            // uncomment below to test the property
            //modelInstance.sign shouldBe ("TODO")
        }

        // to test the property `usergroup`
        should("test usergroup") {
            // uncomment below to test the property
            //modelInstance.usergroup shouldBe ("TODO")
        }

    }
}
