/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import moe.kurenai.bangumi.models.LegacyMonoInfo
import moe.kurenai.bangumi.models.LegacyMonoInfoAlias
import moe.kurenai.bangumi.models.LegacyMonoInfoSource

class LegacyMonoInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LegacyMonoInfo
        //val modelInstance = LegacyMonoInfo()

        // to test the property `birth` - 生日
        should("test birth") {
            // uncomment below to test the property
            //modelInstance.birth shouldBe ("TODO")
        }

        // to test the property `height` - 身高
        should("test height") {
            // uncomment below to test the property
            //modelInstance.height shouldBe ("TODO")
        }

        // to test the property `gender` - 性别
        should("test gender") {
            // uncomment below to test the property
            //modelInstance.gender shouldBe ("TODO")
        }

        // to test the property `alias`
        should("test alias") {
            // uncomment below to test the property
            //modelInstance.alias shouldBe ("TODO")
        }

        // to test the property `source`
        should("test source") {
            // uncomment below to test the property
            //modelInstance.source shouldBe ("TODO")
        }

        // to test the property `nameCn` - 简体中文名
        should("test nameCn") {
            // uncomment below to test the property
            //modelInstance.nameCn shouldBe ("TODO")
        }

        // to test the property `cv` - 声优
        should("test cv") {
            // uncomment below to test the property
            //modelInstance.cv shouldBe ("TODO")
        }

    }
}
