/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import io.kotlintest.specs.ShouldSpec

class LegacyTopicTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LegacyTopic
        //val modelInstance = LegacyTopic()

        // to test the property `id` - ID
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `url` - 地址
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `title` - 标题
        should("test title") {
            // uncomment below to test the property
            //modelInstance.title shouldBe ("TODO")
        }

        // to test the property `mainId` - 所属对象（条目） ID
        should("test mainId") {
            // uncomment below to test the property
            //modelInstance.mainId shouldBe ("TODO")
        }

        // to test the property `timestamp` - 发布时间
        should("test timestamp") {
            // uncomment below to test the property
            //modelInstance.timestamp shouldBe ("TODO")
        }

        // to test the property `lastpost` - 最后回复时间
        should("test lastpost") {
            // uncomment below to test the property
            //modelInstance.lastpost shouldBe ("TODO")
        }

        // to test the property `replies` - 回复数
        should("test replies") {
            // uncomment below to test the property
            //modelInstance.replies shouldBe ("TODO")
        }

        // to test the property `user`
        should("test user") {
            // uncomment below to test the property
            //modelInstance.user shouldBe ("TODO")
        }

    }
}
