/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import io.kotlintest.specs.ShouldSpec

class LegacySubjectMediumAllOfCrtTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LegacySubjectMediumAllOfCrt
        //val modelInstance = LegacySubjectMediumAllOfCrt()

        // to test the property `id` - 人物 ID
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `url` - 人物地址
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `name` - 姓名
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `images`
        should("test images") {
            // uncomment below to test the property
            //modelInstance.images shouldBe ("TODO")
        }

        // to test the property `nameCn` - 简体中文名
        should("test nameCn") {
            // uncomment below to test the property
            //modelInstance.nameCn shouldBe ("TODO")
        }

        // to test the property `comment` - 回复数量
        should("test comment") {
            // uncomment below to test the property
            //modelInstance.comment shouldBe ("TODO")
        }

        // to test the property `collects` - 收藏人数
        should("test collects") {
            // uncomment below to test the property
            //modelInstance.collects shouldBe ("TODO")
        }

        // to test the property `info`
        should("test info") {
            // uncomment below to test the property
            //modelInstance.info shouldBe ("TODO")
        }

        // to test the property `actors` - 声优列表
        should("test actors") {
            // uncomment below to test the property
            //modelInstance.actors shouldBe ("TODO")
        }

        // to test the property `roleName` - 角色类型
        should("test roleName") {
            // uncomment below to test the property
            //modelInstance.roleName shouldBe ("TODO")
        }

    }
}
