/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import io.kotlintest.specs.ShouldSpec

class LegacyEpisodeTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LegacyEpisode
        //val modelInstance = LegacyEpisode()

        // to test the property `id` - 章节 ID
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `url` - 章节地址
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `sort` - 集数
        should("test sort") {
            // uncomment below to test the property
            //modelInstance.sort shouldBe ("TODO")
        }

        // to test the property `name` - 标题
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `nameCn` - 简体中文标题
        should("test nameCn") {
            // uncomment below to test the property
            //modelInstance.nameCn shouldBe ("TODO")
        }

        // to test the property `duration` - 时长
        should("test duration") {
            // uncomment below to test the property
            //modelInstance.duration shouldBe ("TODO")
        }

        // to test the property `airdate` - 放送日期
        should("test airdate") {
            // uncomment below to test the property
            //modelInstance.airdate shouldBe ("TODO")
        }

        // to test the property `comment` - 回复数量
        should("test comment") {
            // uncomment below to test the property
            //modelInstance.comment shouldBe ("TODO")
        }

        // to test the property `desc` - 简介
        should("test desc") {
            // uncomment below to test the property
            //modelInstance.desc shouldBe ("TODO")
        }

        // to test the property `status` - 放送状态 <br> Air = 已放送 <br> Today = 正在放送 <br> NA = 未放送
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

    }
}
