/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import moe.kurenai.bangumi.models.LegacyEpisodeType

class LegacyEpisodeTypeTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LegacyEpisodeType
        //val modelInstance = LegacyEpisodeType()

    }
}
