/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import moe.kurenai.bangumi.models.LegacySubjectSmallCollection

class LegacySubjectSmallCollectionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LegacySubjectSmallCollection
        //val modelInstance = LegacySubjectSmallCollection()

        // to test the property `wish` - 想做
        should("test wish") {
            // uncomment below to test the property
            //modelInstance.wish shouldBe ("TODO")
        }

        // to test the property `collect` - 做过
        should("test collect") {
            // uncomment below to test the property
            //modelInstance.collect shouldBe ("TODO")
        }

        // to test the property `doing` - 在做
        should("test doing") {
            // uncomment below to test the property
            //modelInstance.doing shouldBe ("TODO")
        }

        // to test the property `onHold` - 搁置
        should("test onHold") {
            // uncomment below to test the property
            //modelInstance.onHold shouldBe ("TODO")
        }

        // to test the property `dropped` - 抛弃
        should("test dropped") {
            // uncomment below to test the property
            //modelInstance.dropped shouldBe ("TODO")
        }

    }
}
