/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import io.kotlintest.specs.ShouldSpec

class LegacyMonoInfoAliasTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LegacyMonoInfoAlias
        //val modelInstance = LegacyMonoInfoAlias()

        // to test the property `jp` - 日文名
        should("test jp") {
            // uncomment below to test the property
            //modelInstance.jp shouldBe ("TODO")
        }

        // to test the property `kana` - 纯假名
        should("test kana") {
            // uncomment below to test the property
            //modelInstance.kana shouldBe ("TODO")
        }

        // to test the property `nick` - 昵称
        should("test nick") {
            // uncomment below to test the property
            //modelInstance.nick shouldBe ("TODO")
        }

        // to test the property `romaji` - 罗马字
        should("test romaji") {
            // uncomment below to test the property
            //modelInstance.romaji shouldBe ("TODO")
        }

        // to test the property `zh` - 第二中文名
        should("test zh") {
            // uncomment below to test the property
            //modelInstance.zh shouldBe ("TODO")
        }

    }
}
