/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import io.kotlintest.specs.ShouldSpec

class LegacyUserAvatarTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LegacyUserAvatar
        //val modelInstance = LegacyUserAvatar()

        // to test the property `large`
        should("test large") {
            // uncomment below to test the property
            //modelInstance.large shouldBe ("TODO")
        }

        // to test the property `medium`
        should("test medium") {
            // uncomment below to test the property
            //modelInstance.medium shouldBe ("TODO")
        }

        // to test the property `small`
        should("test small") {
            // uncomment below to test the property
            //modelInstance.small shouldBe ("TODO")
        }

    }
}
