/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import moe.kurenai.bangumi.models.LegacySubjectMedium
import moe.kurenai.bangumi.models.LegacySubjectMediumAllOfCrt
import moe.kurenai.bangumi.models.LegacySubjectMediumAllOfStaff
import moe.kurenai.bangumi.models.LegacySubjectSmallCollection
import moe.kurenai.bangumi.models.LegacySubjectSmallImages
import moe.kurenai.bangumi.models.LegacySubjectSmallRating

class LegacySubjectMediumTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LegacySubjectMedium
        //val modelInstance = LegacySubjectMedium()

        // to test the property `id` - 条目 ID
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `url` - 条目地址
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `type` - 条目类型 - `1` 为 书籍 - `2` 为 动画 - `3` 为 音乐 - `4` 为 游戏 - `6` 为 三次元  没有 `5`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `name` - 条目名称
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `nameCn` - 条目中文名称
        should("test nameCn") {
            // uncomment below to test the property
            //modelInstance.nameCn shouldBe ("TODO")
        }

        // to test the property `summary` - 剧情简介
        should("test summary") {
            // uncomment below to test the property
            //modelInstance.summary shouldBe ("TODO")
        }

        // to test the property `airDate` - 放送开始日期
        should("test airDate") {
            // uncomment below to test the property
            //modelInstance.airDate shouldBe ("TODO")
        }

        // to test the property `airWeekday` - 放送星期
        should("test airWeekday") {
            // uncomment below to test the property
            //modelInstance.airWeekday shouldBe ("TODO")
        }

        // to test the property `images`
        should("test images") {
            // uncomment below to test the property
            //modelInstance.images shouldBe ("TODO")
        }

        // to test the property `eps` - 话数
        should("test eps") {
            // uncomment below to test the property
            //modelInstance.eps shouldBe ("TODO")
        }

        // to test the property `epsCount` - 话数
        should("test epsCount") {
            // uncomment below to test the property
            //modelInstance.epsCount shouldBe ("TODO")
        }

        // to test the property `rating`
        should("test rating") {
            // uncomment below to test the property
            //modelInstance.rating shouldBe ("TODO")
        }

        // to test the property `rank` - 排名
        should("test rank") {
            // uncomment below to test the property
            //modelInstance.rank shouldBe ("TODO")
        }

        // to test the property `collection`
        should("test collection") {
            // uncomment below to test the property
            //modelInstance.collection shouldBe ("TODO")
        }

        // to test the property `crt` - 角色信息
        should("test crt") {
            // uncomment below to test the property
            //modelInstance.crt shouldBe ("TODO")
        }

        // to test the property `staff` - 制作人员信息
        should("test staff") {
            // uncomment below to test the property
            //modelInstance.staff shouldBe ("TODO")
        }

    }
}
