/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import moe.kurenai.bangumi.models.PatchUserSubjectEpisodeCollectionRequest
import moe.kurenai.bangumi.models.EpisodeCollectionType

class PatchUserSubjectEpisodeCollectionRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PatchUserSubjectEpisodeCollectionRequest
        //val modelInstance = PatchUserSubjectEpisodeCollectionRequest()

        // to test the property `episodeId`
        should("test episodeId") {
            // uncomment below to test the property
            //modelInstance.episodeId shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

    }
}
