/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import io.kotlintest.specs.ShouldSpec

class PersonRevisionDataItemTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PersonRevisionDataItem
        //val modelInstance = PersonRevisionDataItem()

        // to test the property `prsnInfobox`
        should("test prsnInfobox") {
            // uncomment below to test the property
            //modelInstance.prsnInfobox shouldBe ("TODO")
        }

        // to test the property `prsnSummary`
        should("test prsnSummary") {
            // uncomment below to test the property
            //modelInstance.prsnSummary shouldBe ("TODO")
        }

        // to test the property `profession`
        should("test profession") {
            // uncomment below to test the property
            //modelInstance.profession shouldBe ("TODO")
        }

        // to test the property `extra`
        should("test extra") {
            // uncomment below to test the property
            //modelInstance.extra shouldBe ("TODO")
        }

        // to test the property `prsnName`
        should("test prsnName") {
            // uncomment below to test the property
            //modelInstance.prsnName shouldBe ("TODO")
        }

    }
}
