/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import io.kotlintest.specs.ShouldSpec

class SearchSubjectByKeywords200ResponseOneOf1Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of SearchSubjectByKeywords200ResponseOneOf1
        //val modelInstance = SearchSubjectByKeywords200ResponseOneOf1()

        // to test the property `results` - 总条数
        should("test results") {
            // uncomment below to test the property
            //modelInstance.results shouldBe ("TODO")
        }

        // to test the property `list` - 结果列表
        should("test list") {
            // uncomment below to test the property
            //modelInstance.list shouldBe ("TODO")
        }

    }
}
