/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package moe.kurenai.bangumi.models

import io.kotlintest.specs.ShouldSpec

class VTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of V
        //val modelInstance = V()

        // to test the property `v`
        should("test v") {
            // uncomment below to test the property
            //modelInstance.v shouldBe ("TODO")
        }

    }
}
